
/*DOMAIN BOOLEAN FIREBIRD 2.5 DEFAULT DO NOT SUPORT BOOLEAN TYPE*/
CREATE DOMAIN BOOLEAN
AS SMALLINT
CHECK (value is null or value in (0, 1));

/*USUARIOS*/
CREATE TABLE USUARIOS (
	ID_USUARIO INT NOT  NULL  PRIMARY  KEY,
	NOME_FUNCIONARIO VARCHAR(80) NOT NULL,
	NOME_USUARIO VARCHAR(60) NOT NULL,
	SENHA VARCHAR(20) NOT NULL,
	ADMINISTRADOR BOOLEAN,
	ULTIMA_ALTERACAO DATE,
	INCLUIR BOOLEAN, 
	ALTERAR BOOLEAN, 
	EXCLUIR BOOLEAN
);

CREATE SEQUENCE usuarios_id_sequence;


CREATE TRIGGER USUARIOS_AUTOINCREMENT FOR USUARIOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  NEW.ID_USUARIO = next value for usuarios_id_sequence;
END;


INSERT INTO USUARIOS (
	NOME_FUNCIONARIO,
	NOME_USUARIO,
	SENHA,
	ADMINISTRADOR,
	ULTIMA_ALTERACAO,
	INCLUIR, 
	ALTERAR, 
	EXCLUIR)
	VALUES (
		'Administrador',
		'ADMIN',
		'SENHA',
		1,
		CURRENT_DATE,
		1,
		1,
		0
		);
		
/*DOCUMENTOS*/

CREATE TABLE DOCUMENTOS (
	ID_DOCUMENTO INT NOT  NULL  PRIMARY  KEY,
	CODIGO INT NOT NULL,
	DESCRICAO VARCHAR(60) NOT NULL,
	UTILIZA_NUM_ANO BOOLEAN
);

CREATE SEQUENCE documentos_id_sequence;


CREATE TRIGGER DOCUMENTOS_AUTOINCREMENT FOR DOCUMENTOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  NEW.ID_DOCUMENTO = next value for documentos_id_sequence;
END;

/*INTERESSADOS*/

CREATE TABLE INTERESSADOS (
	ID_INTERESSADO INT NOT  NULL  PRIMARY  KEY,
	CODIGO INT NOT NULL,
	DESCRICAO VARCHAR(80) NOT NULL
);

CREATE SEQUENCE interessados_id_sequence;


CREATE TRIGGER INTERESSADOS_AUTOINCREMENT FOR INTERESSADOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  NEW.ID_INTERESSADO = next value for interessados_id_sequence;
END;


/*DESTINATARIOS*/
CREATE TABLE DESTINATARIOS (
	ID_DESTINATARIO INT NOT  NULL  PRIMARY  KEY,
	CODIGO INT NOT NULL,
	DESCRICAO VARCHAR(60) NOT NULL,
	EMAIL VARCHAR(60),
	ID_USUARIO INT NOT NULL
);

CREATE SEQUENCE destinatarios_id_sequence;


CREATE TRIGGER DESTINATARIOS_AUTOINCREMENT FOR DESTINATARIOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  NEW.ID_DESTINATARIO = next value for destinatarios_id_sequence;
END;

ALTER TABLE DESTINATARIOS 
ADD FOREIGN KEY(ID_USUARIO)
REFERENCES USUARIOS(ID_USUARIO);
		
/*REGISTROS*/

CREATE TABLE REGISTROS (
	ID_REGISTRO INT NOT  NULL  PRIMARY  KEY,
	ASSUNTO VARCHAR(100) NOT NULL,
	NUM_DOC VARCHAR(10) NOT NULL,
	ANO_DOC VARCHAR(10) NOT NULL,
	DATA_INCLUSAO DATE,
	PROCEDENCIA VARCHAR(60),
	ID_TIPO_DOC INT NOT NULL,
	ID_INTERESSADO INT NOT NULL,
	ID_USUARIO INT NOT NULL
);

CREATE SEQUENCE registros_id_sequence;


CREATE TRIGGER REGISTROS_AUTOINCREMENT FOR REGISTROS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  NEW.ID_REGISTRO = next value for registros_id_sequence;
END;

ALTER TABLE REGISTROS 
ADD FOREIGN KEY(ID_INTERESSADO)
REFERENCES INTERESSADOS(ID_INTERESSADO);

ALTER TABLE REGISTROS 
ADD FOREIGN KEY(ID_TIPO_DOC)
REFERENCES DOCUMENTOS(ID_DOCUMENTO);

ALTER TABLE REGISTROS 
ADD FOREIGN KEY(ID_USUARIO)
REFERENCES USUARIOS(ID_USUARIO);


/*HISTORICO_REGISTROS*/

CREATE TABLE HISTORICO_REGISTROS (
	ID_HISTORICO INT NOT  NULL  PRIMARY  KEY,
	ID_REGISTRO INT NOT NULL,
	DATA_ENTRADA DATE,
	HORA_ENTRADA VARCHAR(8),
	ID_DESTINAT_ORIGEM INT NOT NULL,
	DATA_SAIDA DATE,
	HORA_SAIDA VARCHAR(8),
	ID_DESTINAT_DESTINO INT NOT NULL,
	OBSERVACAO VARCHAR(100),
	DATA_INCLUSAO DATE,
	HORA_INCLUSAO VARCHAR(8),
	ID_USUARIO INT NOT NULL
);

CREATE SEQUENCE hist_registros_id_sequence;


CREATE TRIGGER HIST_REGISTROS_AUTOINCREMENT FOR HISTORICO_REGISTROS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  NEW.ID_HISTORICO = next value for hist_registros_id_sequence;
END;

ALTER TABLE HISTORICO_REGISTROS 
ADD FOREIGN KEY(ID_REGISTRO)
REFERENCES REGISTROS(ID_REGISTRO);

ALTER TABLE HISTORICO_REGISTROS 
ADD FOREIGN KEY(ID_DESTINAT_ORIGEM)
REFERENCES DESTINATARIOS(ID_DESTINATARIO);

ALTER TABLE HISTORICO_REGISTROS 
ADD FOREIGN KEY(ID_DESTINAT_DESTINO)
REFERENCES DESTINATARIOS(ID_DESTINATARIO);

ALTER TABLE HISTORICO_REGISTROS 
ADD FOREIGN KEY(ID_USUARIO)
REFERENCES USUARIOS(ID_USUARIO);


/*AGREGADOS*/

CREATE TABLE AGREGADOS (
	ID_AGREGADO INT NOT NULL PRIMARY KEY,
	ID_INTERESSADO_PRINCIPAL INT NOT NULL,
	CODIGO INT NOT NULL,
	DESCRICAO VARCHAR(80),
	ID_REGISTRO INT NOT NULL
);

ALTER TABLE AGREGADOS 
ADD FOREIGN KEY(ID_INTERESSADO_PRINCIPAL)
REFERENCES INTERESSADOS(ID_INTERESSADO);

ALTER TABLE AGREGADOS 
ADD FOREIGN KEY(ID_REGISTRO)
REFERENCES REGISTROS(ID_REGISTRO);
 
/*DROP TABLE AGREGADOS;
DROP TABLE HISTORICO_REGISTROS;
DROP TABLE REGISTROS;
DROP TABLE INTERESSADOS;
DROP TABLE DESTINATARIOS ;
DROP TABLE DOCUMENTOS;
DROP TABLE USUARIOS;*/
     